export const ALL_CATEGORY_REQUEST = 'ALL_CATEGORY_REQUEST'
export const ALL_CATEGORY_SUCCESS = 'ALL_CATEGORY_SUCCESS'
export const ALL_CATEGORY_FAIL = 'ALL_CATEGORY_FAIL'



export const All_PRODUCTS_REQUEST = 'ALL_PRODUCT_REQUEST'
export const All_PRODUCTS_SUCCESS = 'ALL_PRODUCT_SUCCESS'
export const All_PRODUCTS_FAIL = 'ALL_PRODUCT_FAIL'


export const ADD_TO_CARD = 'ADD_TO_CARD'
export const REMOVE_FROM_CARD  = 'REMOVE_FROM_CARD '
export const LOAD_CARD = 'LOAD_CARD'


export const PRODUCT_PER_PAGE = 8